### ISSUE TITLE
When solution is written to divided CGNS files, the last CGNS file is not closed properly even cg_iRIC_Flush() is called

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/iriclib#4]
When solution is written to divided CGNS files, the last CGNS file is not closed properly even cg_iRIC_Flush() is called.

For example, when the CGNS file is Case1.cgn, the solutions are written to Case1_Solution1.cgn, Case1_Solution2.cgn, ... 

But even user calls cg_iRIC_Flush(), the last file (ex. Case1_SolutioinN.cgn) is not closed properly.

**Comment by scharlton2** [comment]
Hi Keisuke,

I accidently merged your pull request #6.  I reset the HEAD pointer to 2d12ed1 using this command:
`git reset 2d12ed106ee1fbe3f180b69827bf6ed99818218e`
followed by:
`git push --force`

I was able to reopen this issue but was unable to reopen your original pull request.  Can you resubmit your pull request?  I hope I didn't mess things up too much.

Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

I remotely merged in your issue-4 branch so that you don't need to resubmit your previous pull request.

Scott

**Comment by scharlton2** [comment]
Hi Keisuke,

When running unittests_cgnsfile on the latest master branch (1984122) this issue reappeared.

Scott
