### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by mdpiper** [i-RIC/iriclib#58]
@rmcd-mscb and I are building a version of FaSTMECH that can be wrapped in Python. We use iriclib as a dependency to build FaSTMECH on Linux and macOS. Just to be sure that we're using iriclib properly as open source software, it would be helpful if this repository had a license file.

GitHub has more information on licensing open source software projects [here](https://help.github.com/en/articles/licensing-a-repository).

**Comment by kskinoue0612** [comment]
Hi Mark,

Thanks for your contact,
I agree that we should add a license, so that anyone can use the software without worries.

Before we add a license file, we are going to make an agreement about the decision in the next iRIC organization meeting. Please give us some time.
Thanks,

Keisuke

**Comment by mdpiper** [comment]
Hi Keisuke,

Thank you for your response. I'm happy that you'll be adding a license to iriclib. May I ask when the next iRIC meeting will be? I only ask because my request is mildly time-sensitive; the project that Rich and I are working on expires at the end of September, and I hope to have the build process for the models that rely on iriclib in place before then.

Thanks and regards,
Mark

**Comment by kskinoue0612** [comment]
Closed with 83d81bc8942658e4e62e44077f86f543191f3e88 .

LICENSE file with MIT License added.
