### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by mdpiper** [i-RIC/iriclib#59]
To build [conda binaries](https://github.com/csdms-stack/iriclib-recipe) for iriclib on macOS and Linux, I'm staging against a commit (a6a110f117e9a6b1584289621426917a2cfdf487). It would be helpful if I could instead build against an official iriclib [release](https://github.com/i-RIC/iriclib/releases). A `git tag` on a recent commit would work.

**Comment by scharlton2** [comment]
Created releases (tags) for mdpiper.  a6a110f is v0.1 and 7cc7034 is v0.2.
