### ISSUE TITLE
Add function to read / write calculation result values defined at cell edges

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/iriclib#63]
Add function to read / write calculation result values defined at cell edges.
Functions should handle I-direction edge values and J-direction edge values separately.

**Comment by scharlton2** [comment]
Based on i-RIC/iriclib#15

## Functions to add (for the 2D case):

For C/C++:
- cg_iRIC_Write_Sol_IFace_Integer_Mul(int fid, char* name, int* data)
- cg_iRIC_Write_Sol_IFace_Real_Mul(int fid, char* name, double* data)
- cg_iRIC_Write_Sol_IFace_Integer(char* name, int* data)
- cg_iRIC_Write_Sol_IFace_Real(char* name, double* data)
- cg_iRIC_Write_Sol_JFace_Integer_Mul(int fid, char* name, int* data)
- cg_iRIC_Write_Sol_JFace_Real_Mul(int fid, char* name, double* data)
- cg_iRIC_Write_Sol_JFace_Integer(char* name, int* data)
- cg_iRIC_Write_Sol_JFace_Real(char* name, double* data)

For FORTRAN:
- cg_iric_write_sol_iface_integer_mul_f(fid, name, data, ier)
- cg_iric_write_sol_iface_real_mul_f(fid, name, data, ier)
- cg_iric_write_sol_iface_integer_f(name, data, ier)
- cg_iric_write_sol_iface_real_f(name, data, ier)
- cg_iric_write_sol_jface_integer_mul_f(fid, name, data, ier)
- cg_iric_write_sol_jface_real_mul_f(fid, name, data, ier)
- cg_iric_write_sol_jface_integer_f(name, data, ier)
- cg_iric_write_sol_jface_real_f(name, data, ier)

## How to record results in CGNS files

Currently, calculation results defined at grid nodes are stored in FlowSolution_t nodes named "FlowSolution1", "FlowSolution2",... The names of the nodes are stored in "FlowSolutionPointers" in "ZoneIterativeData".

For calculation results defined at grid faces, data are stored in FlowSolution_t nodes with GridLocation_t value IFaceCenter and JFaceCenter, named "FlowIFaceSolution1", "FlowIFaceSolution2", ... and "FlowJFaceSolution1", "FlowJFaceSolution2"... The names of the nodes are stored in "FlowIFaceSolutionPointers" and "FlowJFaceSolutionPointers" in "ZoneIterativeData".

## How to implement

1. CgnsFile::Impl::addSolutionNode() should add "FlowIFaceSolution1", "FlowJFaceSolution1" , etc.
2. Implement CgnsFile::Impl::writeFlowIFaceSolutionPointers() and CgnsFile::Impl::writeFlowJFaceSolutionPointers(), to do similar things to CgnsFile::Impl::writeFlowSolutionPointers().
3. Define CgnsFile::SolutionWriter::Sol_Write_IFace_Integer(), CgnsFile::SolutionWriter::Sol_Write_IFace_Real() as pure virtual functions, and implement them in subclasses.
4. Add description to iriclib.h, iriclib.cpp, to make it possible to call from C/C++
5. Add description to iric_ftoc.c, to make it possible to call from FORTRAN
6. May want/need to reimplement `CgnsFile::Impl::solIndex(CGNS_ENUMT(GridLocation_t) location, int step)`

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for the comment.
I think this seems good, so please implement in this way.

Thanks,
Keisuke
